name: bip32
description: >-
  A [BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)
  hierarchical deterministic wallet library for Dart and Flutter.
version: 4.0.0
homepage: https://github.com/bulltechnologies/bip32
repository: https://github.com/bulltechnologies/bip32
issue_tracker: https://github.com/bulltechnologies/bip32/issues
publish_to: none

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  native_crypto:
    git:
      url: https://github.com/bulltechnologies/native_crypto.git
      ref: a98a33c7331d07a08f2ea3e8585603c172da7fc7
  native_sig:
    git:
      url: https://github.com/bulltechnologies/native_sig.git
      ref: 397fae8d4212c7778b0a0c8b54d3e2c4be406787

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hex: ^0.2.0
  path: ^1.9.0
