name: bip32
description: >-
  A [BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)
  hierarchical deterministic wallet library for Dart and Flutter.
version: 4.0.0
homepage: https://github.com/bulltechnologies/bip32
repository: https://github.com/bulltechnologies/bip32
issue_tracker: https://github.com/bulltechnologies/bip32/issues
publish_to: none

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  native_crypto:
    git:
      url: https://github.com/bulltechnologies/native_crypto.git
      ref: b717f9b5ef50eb3048f7a5a5bf8fea79bd2bb0ec
  native_sig:
    git:
      url: https://github.com/bulltechnologies/native_sig.git
      ref: fb2d66bc5abdc2291146a46f6c39db4844abbac5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hex: ^0.2.0
  path: ^1.9.0
